name: CI

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  python-checks:
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    uses: finleyfamily/workflows/.github/workflows/python.checks.yml@master
    with:
      node-version: '20'
      poetry-plugins: poetry-dynamic-versioning[plugin]
      python-version: ${{ matrix.python-version }}
  python-build:
    needs:
      - python-checks
    uses: finleyfamily/workflows/.github/workflows/python.build.yml@master
    with:
      poetry-plugins: poetry-dynamic-versioning[plugin]
  spellcheck:
    uses: finleyfamily/workflows/.github/workflows/spellcheck.yml@master
    with:
      node-version: '20'
  publish-test-pypi:
    name: 🚀 Publish 📦 To Test PyPI
    if: github.event_name == 'push' && github.ref_name == 'master'
    needs:
      - python-checks
      - python-build
      - spellcheck
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/sphinxcontrib.external-links
    permissions:
      id-token: write
    steps:
      - name: ⤵️ Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - name: 🚀 Publish 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/
