name: Publish Release

on:
  release:
    types:
      - published

env:
  DEFAULT_PYTHON_VERSION: 3.12

jobs:
  python-build:
    uses: finleyfamily/workflows/.github/workflows/python.build.yml@master
    with:
      poetry-plugins: poetry-dynamic-versioning[plugin]
  publish-pypi:
    name: ⤴️ Publish 📦 To PyPI
    needs:
      - python-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - uses: ITProKyle/action-setup-python@v1.0.0
        with:
          poetry-install: false
          poetry-plugins: poetry-dynamic-versioning[plugin]
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install Poetry Plugins
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Publish Distribution 📦 to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
